# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'HomeWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork
  pod 'Alamofire','5.7.1'
  pod 'ObjectMapper', '4.4.2'
  pod 'Kingfisher','7.7.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'ZLPhotoBrowser', :git => 'https://github.com/lleihai123hai1/ZLPhotoBrowser.git'
  
  target 'HomeWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomeWorkUITests' do
    # Pods for testing
  end

end



post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                    if target.name == 'Toast-Swift'
                        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                    end
               end
          end
   end
end
